/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyCompletion {
  'completedAt' : bigint,
  'date' : string,
  'taskId' : bigint,
}
export interface Task {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'daysOfWeek' : Array<bigint>,
  'time' : string,
  'notes' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / ADD TASK
   */
  'addTask' : ActorMethod<[string, string, Array<bigint>, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / DELETE TASK
   */
  'deleteTask' : ActorMethod<[bigint], boolean>,
  /**
   * / GET ALL USERS SUMMARY (ADMIN ONLY)
   */
  'getAllUsersSummary' : ActorMethod<
    [],
    Array<{ 'taskCount' : bigint, 'userPrincipal' : string }>
  >,
  /**
   * / GET CALLER USER PROFILE
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / GET COMPLETIONS FOR DATE
   */
  'getCompletionsForDate' : ActorMethod<[string], Array<DailyCompletion>>,
  /**
   * / GET TASKS (SORTED BY TIME)
   */
  'getTasks' : ActorMethod<[], Array<Task>>,
  /**
   * / GET USER PROFILE
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / MARK TASK DONE
   */
  'markTaskDone' : ActorMethod<[bigint, string], boolean>,
  /**
   * / SAVE CALLER USER PROFILE
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / UNMARK TASK DONE
   */
  'unmarkTaskDone' : ActorMethod<[bigint, string], boolean>,
  /**
   * / UPDATE TASK
   */
  'updateTask' : ActorMethod<
    [bigint, string, string, Array<bigint>, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];