/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DailyCompletion = IDL.Record({
  'completedAt' : IDL.Int,
  'date' : IDL.Text,
  'taskId' : IDL.Nat,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'daysOfWeek' : IDL.Vec(IDL.Nat),
  'time' : IDL.Text,
  'notes' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllUsersSummary' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({ 'taskCount' : IDL.Nat, 'userPrincipal' : IDL.Text })
        ),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletionsForDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DailyCompletion)],
      ['query'],
    ),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markTaskDone' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unmarkTaskDone' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DailyCompletion = IDL.Record({
    'completedAt' : IDL.Int,
    'date' : IDL.Text,
    'taskId' : IDL.Nat,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'daysOfWeek' : IDL.Vec(IDL.Nat),
    'time' : IDL.Text,
    'notes' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllUsersSummary' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({ 'taskCount' : IDL.Nat, 'userPrincipal' : IDL.Text })
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletionsForDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DailyCompletion)],
        ['query'],
      ),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markTaskDone' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unmarkTaskDone' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };